### PR TITLE
Fix  contact animation

### PR DESCRIPTION
**Pull request by Dhruv127**

### CODE REVIEW

**Comment by Sofiyana-1811** [comment]
@Dhruv127 looks good to me, please check the colors once, smoothen the transition as seen in the video or figma file prototype, and also the position and size of arrow in hover state is a bit weird, fix that, the basic animation seems good.

**Comment by Sofiyana-1811** [comment]
@Dhruv127 have you checked the figma file?

**Comment by Dhruv127** [comment]
yeah.. but today are my quizzes.. so can you kindly extend the deadline till the 20th? However will try to complete by eod.

**Comment by Sofiyana-1811** [comment]
Sure, I can extend it

**Comment by Dhruv127** [comment]
Will this work now?

**Comment by Sofiyana-1811** [comment]
Very impressive work till now. The positioning is perfect now. Can you animate the "contact" word such that it goes right and into two lines letter by letter (using flex shrink maybe) and make the animation a bit more smooth and bubbly? Also the top left corner of the orange box to be animated as if we fold a paper, see once if that is possible, as the current animation is just change in opacity, which is not what we exactly desire.  Just check in the duration so the animation feels a bit more smooth.

**Comment by Dhruv127** [comment]
sorry , i don't know how to handle that contact text splitting part .. . Thats why I used an image instead.

**Pull request merged**
