### PR TITLE
Fix menu feature

### PR DESCRIPTION
**Pull request by Dhruv127**

### CODE REVIEW

**Comment by Sofiyana-1811** [comment]
Use SVG instead of icons, the error in deployment is due to the icon.

**Comment by Sofiyana-1811** [comment]
@Dhruv127 We dont want the navbar width to increase with the dropdown, that bug needs to be fixed, the navbar width must be fixed and independent of the drop down, also use the same SVG which is there in the figma file.

**Comment by Dhruv127** [comment]
I can't find figma file , can you share the linl

**Comment by Dhruv127** [comment]
done

**Comment by Sofiyana-1811** [comment]
image
as you can see, the navbar width still increases with the dropdown, the dropdown shouldnt interfere with the navbar width, kjust like any normal dropdown component, try fixing that and smoothening the transition.

**Comment by Dhruv127** [comment]
kindly check , is this fine..?

**Comment by Dhruv127** [comment]
do check if it's good now ?..

**Comment by Sofiyana-1811** [comment]
Great Work, just a few minor changes. 
image
make this vertically centre aligned.

also drop the text "close" just let the svg remain, also make a few changes in the svg, you can directly use "classname" tag on svg and put tailwind properties - make the size 14 x 14 pixels, set its color to the white font color in dark mode and the black font color in light mode.

image
also when any of the links are opened, we want the drop down to automatically close otherwise it looks like this.

**Comment by Dhruv127** [comment]
kindly check now .

**Comment by Sofiyana-1811** [comment]
looks good to me, just let @bedanta12  see it once, I think it is fine

**Comment by Sofiyana-1811** [comment]
@Dhruv127 the working is fine, just add this feature that when we interact with outside of the dropdown then also it closes, for example if I opened it and then  started scrolling or tapping on other elements, the menu should close.

**Comment by Dhruv127** [comment]
ok, I added this. The menu dropdown should close, on scroll also... now, Kindly check.

**Pull request merged**
